'use strict';
const{newId,now,required,mapRow,mapRows}=require('./common.cjs');const{protect,PersistenceError}=require('../errors.cjs');
module.exports=function bugs(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const projectId=required(input.projectId,'projectId');if(input.requirementId){const r=q('SELECT project_id FROM requirements WHERE id=?').get(input.requirementId);if(!r||r.project_id!==projectId)throw new PersistenceError('VALIDATION','Bug requirement must belong to the same project');}if(input.sessionId){const s=q('SELECT r.project_id FROM workflow_sessions w JOIN requirements r ON r.id=w.requirement_id WHERE w.id=?').get(input.sessionId);if(!s||s.project_id!==projectId)throw new PersistenceError('VALIDATION','Bug session must belong to the same project');}const id=input.id||newId();q('INSERT INTO bugs(id,project_id,requirement_id,workflow_session_id,title,description,severity,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,projectId,input.requirementId||null,input.sessionId||null,required(input.title,'title'),input.description||'',input.severity||'medium',input.status||'open',now());return mapRow(q('SELECT * FROM bugs WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM bugs WHERE id=?').get(required(id,'id'))));},
 list({projectId,requirementId,status}={}){return protect(()=>{let sql='SELECT * FROM bugs WHERE 1=1',p=[];for(const[k,c]of [['projectId','project_id'],['requirementId','requirement_id'],['status','status']])if(({projectId,requirementId,status})[k]){sql+=` AND ${c}=?`;p.push(({projectId,requirementId,status})[k]);}return mapRows(q(sql+' ORDER BY created_at DESC').all(...p));});},
 linkTask(id,taskId,relation='discovered_by'){return protect(()=>{const b=q('SELECT project_id,requirement_id FROM bugs WHERE id=?').get(required(id,'bugId'));const t=q('SELECT r.project_id,t.requirement_id FROM tasks t JOIN requirements r ON r.id=t.requirement_id WHERE t.id=?').get(required(taskId,'taskId'));if(!b||!t)throw new PersistenceError('NOT_FOUND','Bug or task not found');if(b.project_id!==t.project_id||(b.requirement_id&&b.requirement_id!==t.requirement_id))throw new PersistenceError('VALIDATION','Bug and task must belong to the same project and requirement');q('INSERT OR IGNORE INTO bug_tasks(bug_id,task_id,relation) VALUES(?,?,?)').run(id,taskId,relation);return mapRows(q('SELECT * FROM bug_tasks WHERE bug_id=?').all(id));});},
 update(id,input={}){return protect(()=>{const f={title:'title',description:'description',severity:'severity',status:'status'},s=[],v=[];for(const[k,c]of Object.entries(f))if(Object.hasOwn(input,k)){s.push(`${c}=?`);v.push(input[k]);}if(s.length)q(`UPDATE bugs SET ${s.join(',')} WHERE id=?`).run(...v,required(id,'id'));return mapRow(q('SELECT * FROM bugs WHERE id=?').get(id));});}
};};
