'use strict';
const{newId,now,required,mapRow,mapRows}=require('./common.cjs');const{protect,PersistenceError}=require('../errors.cjs');
module.exports=function decisions(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const id=input.id||newId(),t=now();q('INSERT INTO decisions(id,project_id,requirement_id,workflow_session_id,decision_type,status,question,result_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,required(input.projectId,'projectId'),required(input.requirementId,'requirementId'),input.sessionId||null,input.decisionType||null,input.status||'open',input.question||'',JSON.stringify(input.result||{}),t,t);return mapRow(q('SELECT * FROM decisions WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM decisions WHERE id=?').get(required(id,'id'))));},
 update(id,input={}){return protect(()=>{const fields={status:'status',question:'question',result:'result_json'},sets=[],values=[];for(const[k,c]of Object.entries(fields))if(Object.hasOwn(input,k)){sets.push(`${c}=?`);values.push(k==='result'?JSON.stringify(input[k]):input[k]);}if(sets.length){sets.push('updated_at=?');values.push(now(),required(id,'id'));q(`UPDATE decisions SET ${sets.join(',')} WHERE id=?`).run(...values);}return mapRow(q('SELECT * FROM decisions WHERE id=?').get(id));});},
 list({requirementId,projectId}={}){return protect(()=>{let sql='SELECT * FROM decisions WHERE 1=1',p=[];if(requirementId){sql+=' AND requirement_id=?';p.push(requirementId);}if(projectId){sql+=' AND project_id=?';p.push(projectId);}return mapRows(q(sql+' ORDER BY created_at DESC').all(...p));});},
 linkTask(id,taskId,relation='informs'){return protect(()=>{const d=q('SELECT requirement_id FROM decisions WHERE id=?').get(required(id,'decisionId'));if(!d)throw new PersistenceError('NOT_FOUND','Decision not found');q('INSERT OR IGNORE INTO decision_tasks(decision_id,task_id,requirement_id,relation) VALUES(?,?,?,?)').run(id,required(taskId,'taskId'),d.requirement_id,relation);return mapRows(q('SELECT * FROM decision_tasks WHERE decision_id=?').all(id));});},
 appendEvent(id,input={}){return protect(()=>db.withTransaction(()=>{id=required(id,'decisionId');if(input.idempotencyKey){const old=q('SELECT * FROM decision_events WHERE decision_id=? AND event_type=? AND idempotency_key=?').get(id,required(input.eventType,'eventType'),input.idempotencyKey);if(old)return mapRow(old);}const seq=Number(q('SELECT COALESCE(MAX(sequence),0)+1 n FROM decision_events WHERE decision_id=?').get(id).n),eventId=input.id||newId();q('INSERT INTO decision_events(id,decision_id,sequence,event_type,payload_json,actor_type,actor_id,occurred_at,origin_environment_id,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?,?)').run(eventId,id,seq,required(input.eventType,'eventType'),JSON.stringify(input.payload||{}),input.actorType||'system',input.actorId||null,input.occurredAt||now(),input.environmentId||null,input.idempotencyKey||null);return mapRow(q('SELECT * FROM decision_events WHERE id=?').get(eventId));}));},
 events(id){return protect(()=>mapRows(q('SELECT * FROM decision_events WHERE decision_id=? ORDER BY sequence').all(required(id,'decisionId'))));}
};};
