'use strict';const{newId,now,required,mapRow,mapRows}=require('./common.cjs');const{protect,PersistenceError}=require('../errors.cjs');
module.exports=function proposals(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const projectId=required(input.projectId,'projectId');if(input.requirementId){const r=q('SELECT project_id FROM requirements WHERE id=?').get(input.requirementId);if(!r||r.project_id!==projectId)throw new PersistenceError('VALIDATION','Proposal requirement must belong to the same project');}const id=input.id||newId(),t=now();q('INSERT INTO proposals(id,project_id,requirement_id,status,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,projectId,input.requirementId||null,input.status||'proposed',JSON.stringify(input.payload||{}),t,t);return mapRow(q('SELECT * FROM proposals WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM proposals WHERE id=?').get(required(id,'id'))));},
 list({projectId,status}={}){return protect(()=>{let sql='SELECT * FROM proposals WHERE 1=1',p=[];if(projectId){sql+=' AND project_id=?';p.push(projectId);}if(status){sql+=' AND status=?';p.push(status);}return mapRows(q(sql+' ORDER BY updated_at DESC').all(...p));});},
 createEvent(id,input={}){return protect(()=>{const eventId=input.id||newId(),t=now();q('INSERT INTO proposal_events(id,proposal_id,event_type,payload_json,occurred_at) VALUES(?,?,?,?,?)').run(eventId,required(id,'proposalId'),required(input.eventType,'eventType'),JSON.stringify(input.payload||{}),t);return mapRow(q('SELECT * FROM proposal_events WHERE id=?').get(eventId));});},
 updateStatus(id,status){return protect(()=>{const t=now();q('UPDATE proposals SET status=?,updated_at=? WHERE id=?').run(required(status,'status'),t,required(id,'proposalId'));return mapRow(q('SELECT * FROM proposals WHERE id=?').get(id));});},
 events(id){return protect(()=>mapRows(q('SELECT * FROM proposal_events WHERE proposal_id=? ORDER BY occurred_at,id').all(required(id,'proposalId'))));}
};};
