'use strict';
const {newId,now,required,mapRow,mapRows,assertRevision}=require('./common.cjs'); const {protect,PersistenceError}=require('../errors.cjs');
module.exports=function requirements(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const id=input.id||newId(),t=now();q(`INSERT INTO requirements(id,project_id,title,request_text,summary,scope_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,required(input.projectId,'projectId'),required(input.title,'title'),input.requestText||'',input.summary||'',JSON.stringify(input.scope||{}),input.status||'draft',t,t);return mapRow(q('SELECT * FROM requirements WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM requirements WHERE id=?').get(required(id,'id'))));},
 list({projectId,status,limit=100,cursor}={}){return protect(()=>{const n=Math.max(1,Math.min(200,Number(limit)||100));let sql='SELECT * FROM requirements WHERE 1=1',p=[];if(projectId){sql+=' AND project_id=?';p.push(projectId);}if(status){sql+=' AND status=?';p.push(status);}if(cursor){sql+=' AND id>?';p.push(cursor);}const rows=q(sql+' ORDER BY id LIMIT ?').all(...p,n+1),more=rows.length>n,items=mapRows(rows.slice(0,n));return{items,nextCursor:more?items.at(-1).id:null};});},
 update(id,input={}){return protect(()=>db.withTransaction(()=>{id=required(id,'id');const old=q('SELECT * FROM requirements WHERE id=?').get(id);if(!old)throw new PersistenceError('NOT_FOUND','Requirement not found');assertRevision(old.revision,input.expectedRevision,'requirement');const cols={title:'title',requestText:'request_text',summary:'summary',scope:'scope_json',status:'status'};const sets=[],vals=[];for(const[k,c]of Object.entries(cols))if(Object.hasOwn(input,k)){sets.push(`${c}=?`);vals.push(k==='scope'?JSON.stringify(input[k]):input[k]);}if(sets.length){sets.push('revision=revision+1','updated_at=?');vals.push(now(),id);q(`UPDATE requirements SET ${sets.join(',')} WHERE id=?`).run(...vals);}return mapRow(q('SELECT * FROM requirements WHERE id=?').get(id));}));},
 milestones:{
 list(requirementId){return protect(()=>mapRows(q('SELECT * FROM requirement_milestones WHERE requirement_id=? ORDER BY position,id').all(required(requirementId,'requirementId'))));},
 create(input={}){return protect(()=>{const id=input.id||newId();q('INSERT INTO requirement_milestones(id,requirement_id,description,status,position) VALUES(?,?,?,?,?)').run(id,required(input.requirementId,'requirementId'),input.description||'',input.status||'active',input.position||0);return mapRow(q('SELECT * FROM requirement_milestones WHERE id=?').get(id));});},
 update(id,input={}){return protect(()=>{const fields={description:'description',status:'status',position:'position'},s=[],v=[];for(const[k,c]of Object.entries(fields))if(Object.hasOwn(input,k)){s.push(`${c}=?`);v.push(input[k]);}if(s.length)q(`UPDATE requirement_milestones SET ${s.join(',')} WHERE id=?`).run(...v,required(id,'id'));return mapRow(q('SELECT * FROM requirement_milestones WHERE id=?').get(id));});},
 delete(id){return protect(()=>{q('DELETE FROM requirement_milestones WHERE id=?').run(required(id,'id'));return {deleted:true};});},
 setTasks(milestoneId,taskIds=[]){return protect(()=>db.withTransaction(()=>{const m=q('SELECT * FROM requirement_milestones WHERE id=?').get(required(milestoneId,'milestoneId'));if(!m)throw new PersistenceError('NOT_FOUND','Milestone not found');q('DELETE FROM milestone_tasks WHERE milestone_id=?').run(milestoneId);taskIds.forEach((taskId,i)=>q('INSERT INTO milestone_tasks(milestone_id,task_id,requirement_id,position) VALUES(?,?,?,?)').run(milestoneId,taskId,m.requirement_id,i));return mapRows(q(`SELECT t.* FROM tasks t JOIN milestone_tasks mt ON mt.task_id=t.id WHERE mt.milestone_id=? ORDER BY mt.position`).all(milestoneId));}));},
 tasks(milestoneId){return protect(()=>mapRows(q(`SELECT t.* FROM tasks t JOIN milestone_tasks mt ON mt.task_id=t.id WHERE mt.milestone_id=? ORDER BY mt.position`).all(required(milestoneId,'milestoneId'))));},
 }
};};
