'use strict';
const {newId,now,required,mapRow,mapRows}=require('./common.cjs');const{protect,PersistenceError}=require('../errors.cjs');
module.exports=function sessions(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const id=input.id||newId(),t=now();q(`INSERT INTO workflow_sessions(id,requirement_id,kind,status,title,log_dir,origin_environment_id,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,required(input.requirementId,'requirementId'),required(input.kind,'kind'),input.status||'created',input.title||'',input.logDir||`.awf/logs/sessions/${id}`,input.originEnvironmentId||null,t);return mapRow(q('SELECT * FROM workflow_sessions WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM workflow_sessions WHERE id=?').get(required(id,'id'))));},
 list({requirementId,kind,limit=100,cursor}={}){return protect(()=>{let sql='SELECT * FROM workflow_sessions WHERE 1=1',p=[];for(const[k,c]of [['requirementId','requirement_id'],['kind','kind']])if(({requirementId,kind})[k]){sql+=` AND ${c}=?`;p.push(({requirementId,kind})[k]);}if(cursor){sql+=' AND id>?';p.push(cursor);}const n=Math.max(1,Math.min(200,Number(limit)||100)),rows=q(sql+' ORDER BY id LIMIT ?').all(...p,n+1),more=rows.length>n,items=mapRows(rows.slice(0,n));return{items,nextCursor:more?items.at(-1).id:null};});},
 createAttempt(sessionId,input={}){return protect(()=>{const no=Number(q('SELECT COALESCE(MAX(attempt_no),0)+1 AS n FROM session_attempts WHERE workflow_session_id=?').get(required(sessionId,'sessionId')).n),id=input.id||newId(),t=input.startedAt||now();q(`INSERT INTO session_attempts(id,workflow_session_id,attempt_no,environment_id,status,provider,started_at,run_id) VALUES(?,?,?,?,?,?,?,?)`).run(id,sessionId,no,input.environmentId||null,'running',input.provider||null,t,input.runId||null);return mapRow(q('SELECT * FROM session_attempts WHERE id=?').get(id));});},
 markActive(sessionId,startedAt){return protect(()=>{q(`UPDATE workflow_sessions SET status='active',started_at=COALESCE(started_at,?),ended_at=NULL,revision=revision+1 WHERE id=?`).run(required(startedAt,'startedAt'),required(sessionId,'sessionId'));return mapRow(q('SELECT * FROM workflow_sessions WHERE id=?').get(sessionId));});},
 finishAttempt(id,{status='completed',errorText=null}={}){return protect(()=>{const t=now();q('UPDATE session_attempts SET status=?,error_text=?,ended_at=? WHERE id=?').run(status,errorText,t,required(id,'id'));return mapRow(q('SELECT * FROM session_attempts WHERE id=?').get(id));});},
 finish(id,{status='completed'}={}){return protect(()=>{q('UPDATE workflow_sessions SET status=?,ended_at=?,revision=revision+1 WHERE id=?').run(status,now(),required(id,'id'));return mapRow(q('SELECT * FROM workflow_sessions WHERE id=?').get(id));});},
 attempts(sessionId){return protect(()=>mapRows(q('SELECT * FROM session_attempts WHERE workflow_session_id=? ORDER BY attempt_no').all(required(sessionId,'sessionId'))));},
 linkConversation(sessionId,input={}){return protect(()=>{const id=input.id||newId();q('INSERT INTO session_conversations(id,workflow_session_id,provider,external_conversation_id,created_at) VALUES(?,?,?,?,?) ON CONFLICT(provider,external_conversation_id) DO UPDATE SET workflow_session_id=excluded.workflow_session_id').run(id,required(sessionId,'sessionId'),required(input.provider,'provider'),required(input.externalConversationId,'externalConversationId'),now());return mapRow(q('SELECT * FROM session_conversations WHERE provider=? AND external_conversation_id=?').get(input.provider,input.externalConversationId));});},
 conversations(sessionId){return protect(()=>mapRows(q('SELECT * FROM session_conversations WHERE workflow_session_id=? ORDER BY created_at').all(required(sessionId,'sessionId'))));}
};};
