'use strict';
const {newId,now,required,mapRow,mapRows,assertRevision}=require('./common.cjs');const{protect,PersistenceError}=require('../errors.cjs');
module.exports=function tasks(db){const q=s=>db.connection.prepare(s);return{
 create(input={}){return protect(()=>{const id=input.id||newId(),t=now();q(`INSERT INTO tasks(id,requirement_id,task_key,title,kind,status,source,prompt,acceptance,blocked_reason,details_json,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,required(input.requirementId,'requirementId'),required(input.taskKey,'taskKey'),required(input.title,'title'),input.kind||'dev',input.status||'pending',input.source||null,input.prompt||'',input.acceptance||'',input.blockedReason||null,JSON.stringify(input.details||{}),input.position||0,t,t);return mapRow(q('SELECT * FROM tasks WHERE id=?').get(id));});},
 get(id){return protect(()=>mapRow(q('SELECT * FROM tasks WHERE id=?').get(required(id,'id'))));},
 list({requirementId,limit=100,cursor,status}={}){return protect(()=>{let sql='SELECT * FROM tasks WHERE requirement_id=?',p=[required(requirementId,'requirementId')];if(status){sql+=' AND status=?';p.push(status);}if(cursor){sql+=' AND id>?';p.push(cursor);}const n=Math.max(1,Math.min(200,Number(limit)||100)),rows=q(sql+' ORDER BY id LIMIT ?').all(...p,n+1),more=rows.length>n,items=mapRows(rows.slice(0,n));return{items,nextCursor:more?items.at(-1).id:null};});},
 update(id,input={}){return protect(()=>db.withTransaction(()=>{id=required(id,'id');const old=q('SELECT * FROM tasks WHERE id=?').get(id);if(!old)throw new PersistenceError('NOT_FOUND','Task not found');assertRevision(old.revision,input.expectedRevision,'task');const cols={taskKey:'task_key',title:'title',kind:'kind',status:'status',source:'source',prompt:'prompt',acceptance:'acceptance',blockedReason:'blocked_reason',details:'details_json',position:'position'},s=[],v=[];for(const[k,c]of Object.entries(cols))if(Object.hasOwn(input,k)){s.push(`${c}=?`);v.push(k==='details'?JSON.stringify(input[k]):input[k]);}if(s.length){s.push('revision=revision+1','updated_at=?');v.push(now(),id);q(`UPDATE tasks SET ${s.join(',')} WHERE id=?`).run(...v);}return mapRow(q('SELECT * FROM tasks WHERE id=?').get(id));}));},
 dependencies(taskId){return protect(()=>mapRows(q('SELECT t.*,d.position AS dependency_position FROM task_dependencies d JOIN tasks t ON t.id=d.depends_on_task_id WHERE d.task_id=? ORDER BY d.position').all(required(taskId,'taskId'))));},
 setDependencies(taskId,dependencyIds=[]){return protect(()=>db.withTransaction(()=>{const task=q('SELECT * FROM tasks WHERE id=?').get(required(taskId,'taskId'));if(!task)throw new PersistenceError('NOT_FOUND','Task not found');q('DELETE FROM task_dependencies WHERE task_id=?').run(taskId);for(let i=0;i<dependencyIds.length;i++){const dep=dependencyIds[i];if(dep===taskId)throw new PersistenceError('VALIDATION','A task cannot depend on itself');const cycle=q(`WITH RECURSIVE reach(id) AS (SELECT depends_on_task_id FROM task_dependencies WHERE task_id=? UNION SELECT d.depends_on_task_id FROM task_dependencies d JOIN reach r ON d.task_id=r.id) SELECT 1 FROM reach WHERE id=? LIMIT 1`).get(dep,taskId);if(cycle)throw new PersistenceError('VALIDATION','Task dependency would create a cycle');q('INSERT INTO task_dependencies(requirement_id,task_id,depends_on_task_id,position) VALUES(?,?,?,?)').run(task.requirement_id,taskId,dep,i);}return mapRows(q('SELECT t.* FROM task_dependencies d JOIN tasks t ON t.id=d.depends_on_task_id WHERE d.task_id=? ORDER BY d.position').all(taskId));}));},
 addCommit(taskId,input={}){return protect(()=>{const id=input.id||newId();q('INSERT INTO task_commits(id,task_id,hash,message,position,created_at) VALUES(?,?,?,?,?,?)').run(id,required(taskId,'taskId'),required(input.hash,'hash'),input.message||'',input.position||0,now());return mapRow(q('SELECT * FROM task_commits WHERE id=?').get(id));});},
 commits(taskId){return protect(()=>mapRows(q('SELECT * FROM task_commits WHERE task_id=? ORDER BY position,created_at').all(required(taskId,'taskId'))));},
 recordExecution(input={}){return protect(()=>{const id=input.id||newId();q('INSERT INTO task_executions(id,task_id,workflow_session_id,requirement_id,attempt_id,status,result_json,started_at,ended_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,required(input.taskId,'taskId'),required(input.sessionId,'sessionId'),required(input.requirementId,'requirementId'),input.attemptId||null,input.status||'running',JSON.stringify(input.result||{}),input.startedAt||now(),input.endedAt||null);return mapRow(q('SELECT * FROM task_executions WHERE id=?').get(id));});},
 executions(taskId){return protect(()=>mapRows(q('SELECT * FROM task_executions WHERE task_id=? ORDER BY started_at DESC').all(required(taskId,'taskId'))));}
};};
