// Addresses only. HTTP/WS implementation belongs to shared/lib/http.js.
export const API = Object.freeze({
  status: '/status',
  projects: '/api/persistence/projects',
  directories: '/api/persistence/projects',
  selectProjectFolder: '/api/persistence/projects/select-folder',
  initOptions: '/api/persistence/init-options',
  inspectProject: '/api/persistence/projects/inspect',
  initializeProject: '/api/persistence/projects/initialize',
  addProject: '/api/persistence/projects/add',
  workspace: '/api/persistence/workspace',
  workspaceFor: id => `/api/persistence/workspace?requirementId=${encodeURIComponent(id)}`,
  state: '/api/persistence/state',
  requirements: '/api/persistence/requirements',
  createRequirement: '/api/persistence/requirements',
  requirementAction: (id, action) => `/api/persistence/requirements/${encodeURIComponent(id)}/${action}`,
  prepareRequirementWorktree: id => `/api/persistence/requirements/${encodeURIComponent(id)}/prepare-worktree`,
  requirementReview: id => `/api/persistence/requirements/${encodeURIComponent(id)}/review`,
  bugs: '/api/persistence/bugs',
  workConfig: '/api/persistence/work-config',
  workConfigBranches: root => `/api/persistence/work-config/branches?repositoryRoot=${encodeURIComponent(root)}`,
  workClaims: '/api/persistence/work-claims',
  recoverWorkClaim: id => `/api/persistence/work-claims/${encodeURIComponent(id)}/recover`,
  bugAction: (id, action) => `/api/persistence/bugs/${encodeURIComponent(id)}/${action}`,
  prepareBugWorktree: id => `/api/persistence/bugs/${encodeURIComponent(id)}/prepare-worktree`,
  bugReview: id => `/api/persistence/bugs/${encodeURIComponent(id)}/review`,
  preparePlan: '/workflow/plan/start',
  finishPlan: '/workflow/plan/finish',
  generatePlan: '/api/persistence/plan/generate',
  savePlan: '/api/persistence/plan/save',
  approvePlan: '/api/persistence/plan/approve',
  conversation: '/data/conversation',
  sourceLog: '/api/persistence/log-content',
  logFiles: '/api/persistence/log-files',
  cancelRun: id => `/run/${encodeURIComponent(id)}/cancel`,
  retryRun: id => `/run/${encodeURIComponent(id)}/retry`,
  taskAction: (id, action) => `/api/persistence/tasks/${encodeURIComponent(id)}/${action}`,
  proposalAction: (id, action) => `/api/persistence/proposals/${encodeURIComponent(id)}/${action}`,
  snapshot: '/status?snapshot=1',
  runs: '/run/status',
  events: '/run/events',
  submitRun: '/api/persistence/run/start',
  workflowMode: '/run/state/mode',
  send: '/send',
  respond: '/respond',
  stop: '/stop',
  decisions: '/api/persistence/decisions',
  proposals: '/api/persistence/proposals',
  metrics: '/awf/metrics',
  diagnostics: '/awf/diagnostics',
  eventPage: (cursor, limit = 500) => `/run/events?afterSeq=${cursor}&limit=${limit}`,
  resolveDecision: id => `/api/persistence/decisions/${encodeURIComponent(id)}/resolve`,
  overrideDecision: id => `/api/persistence/decisions/${encodeURIComponent(id)}/override`,
  approveDecision: id => `/api/persistence/decisions/${encodeURIComponent(id)}/approve`,
  approveProposal: id => `/api/persistence/proposals/${encodeURIComponent(id)}/approve`,
});
